server:
  port: 9191

spring:
  application:
    name: CLOUD-GATEWAY
  cloud:
    gateway:
      routes:
#           user microservice
        - id: USER-MICROSERVICE
          uri: lb://USER-MICROSERVICE
          predicates:
            - Path=/users/*
          filters:
            - name: CircuitBreaker
              args:
                name: USER-MICROSERVICE
                fallbackuri: forward:/userServiceFallback
#           department microservice
        - id: DEPARTMENT-MICROSERVICE
          uri: lb://DEPARTMENT-MICROSERVICE
          predicates:
            - Path=/departments/*
          filters:
            - name: CircuitBreaker
              args:
                name: DEPARTMENT-MICROSERVICE
                fallbackuri: forward:/departmentServiceFallback

hystrix:
  command:
    fallbackcmd:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 4000

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream
